language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-origin-craft' ]; then cd .. && eval "mv $currentfolder generator-origin-craft" && cd generator-origin-craft; fi

